# Generated by Django 5.0 on 2023-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
    ]
