# Generated by Django 5.0 on 2023-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_password_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
