# Generated by Django 5.0 on 2023-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0003_alter_password_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=False),
        ),
    ]
