# Generated by Django 5.0 on 2023-12-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0005_category_password_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='password.category'),
        ),
    ]
